### ISSUE TITLE
[FEATURE] Admiral support for Istio 1.8 and higher

### ISSUE THREAD

**Issue by anmolagrawal23** [istio-ecosystem/admiral#169]
We are planning to use admiral with istio 1.9 but it is supported till maximum Istio 1.7.4 as per the [compatibility document](https://github.com/istio-ecosystem/admiral/blob/master/docs/Compatibility.md).

Istio has deprecated support for .global stub domain, refer [this](https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/#multicluster-global-stub-domain-deprecation) for more info.

Is there a plan/roadmap for admiral support support with the new istio multi-cluster approach?

**Comment by josephpeacock** [comment]
@anmolagrawal23 We definitely still need to test Admiral with istio 1.8. However, the `.global` stubdomain deprecation shouldn't have any impact on how Admiral functions. That is because Admiral doesn't rely on the built-in Istio `.global` DNS resolution. Rather, it creates serviceentries with the pattern `<env>.<identifier>.<global>`. Because these DNS names are created via serviceentries, they should remain unaffected by that Istio change. Admiral has defaulted to the DNS format with a `.global` suffix to mimic the pattern of Istio's built-in multicluster service discovery, but can be overridden via the `hostname_suffix` param https://github.com/istio-ecosystem/admiral/blob/master/admiral/cmd/admiral/cmd/root.go#L86
